version: "3.9"

services:
  rag-service:
    build: .
    container_name: rag-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_AI_OLLAMA_BASE_URL: http://ollama:11434
      SPRING_AI_VECTORSTORE_CHROMA_BASE_URL: http://chroma:8000
    depends_on:
      - ollama
      - chroma

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5

  chroma:
    image: chromadb/chroma:latest
    container_name: chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    environment:
      CHROMA_SERVER_AUTH: "false"

volumes:
  ollama_data:
  chroma_data:
