spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text
  application:
    name: rag
  management:
    endpoints:
      web:
        exposure:
          include=*:

server:
  port: 8081

rag:
  useConfluence: false
  vectorstore:
    type: chroma   # chroma or postgres
    chroma:
      collection-name: rag_collection
    postgres:
      url: jdbc:postgresql://localhost:5432/rag
      username: rag_user
      password: rag_pass