spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
      embedding:
        options:
          model: all-minilm
      init:
        chat:
          include: false
    vectorstore:
      type: pgvector
      pgvector:
        url: jdbc:postgresql://localhost:5432/rag_db
        username: postgres
        password: password
        table-name: documents

  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  application:
    name: rag
  management:
    endpoints:
      web:
        exposure:
          include=*:

server:
  port: 8081

rag:
  useConfluence: false
  startup: false

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com.akrios.rag: INFO
  pattern:
    console: ${LOG_PATTERN:time=%d{YYYY-MM-DDThh:mm:ss.sssZ}|level=%-5level|app_id=${spring.application.name}|component_id=%C{1.}|corrId=%X{Correlationid}|trace=%X{traceId:-}|span=%X{spanId:-}|%msg%n%throwable}