spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
      embedding:
        options:
          model: all-minilm
      init:
        chat:
          include: false
          pull-model-strategy: WHEN_MISSING
    vectorstore:
      chroma:
        initialize-schema: true
        memory: true
        collection-name: rag_collection

  application:
    name: rag
  management:
    endpoints:
      web:
        exposure:
          include=*:

server:
  port: 8081

rag:
  useConfluence: false