spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
      embedding:
        options:
          model: nomic-embed-text
      pgvector:
        initialize-schema: true
  application:
    name: rag
  management:
    endpoints:
      web:
        exposure:
          include=*:

server:
  port: 8081

rag:
  useConfluence: false
