spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3.2
          temperature: 0.7
      embedding:
        options:
          model: all-minilm
      init:
        chat:
          include: false
          pull-model-strategy: WHEN_MISSING
    vectorstore:
      type: pgvector
      pgvector:
        url: jdbc:postgresql://localhost:5432/rag_db
        username: postgres
        password: password
        table-name: documents

  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: rag
  management:
    endpoints:
      web:
        exposure:
          include=*:

server:
  port: 8081

rag:
  useConfluence: false
  startup: false

logging:
  level:
    com.akrios.rag: INFO